create_generated_clock -name clk_gen_inst/clk_4M_gen/clk_div -source [get_pins clk_gen_inst/pll_inst/inst/mmcm_adv_inst/CLKOUT0] -divide_by 20 [get_pins clk_gen_inst/clk_4M_gen/clk_div_reg/Q]
set_property PACKAGE_PIN Y18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN F15 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN J21 [get_ports RX]
set_property IOSTANDARD LVCMOS33 [get_ports RX]
set_property PACKAGE_PIN M15 [get_ports TX]
set_property IOSTANDARD LVCMOS33 [get_ports TX]
